---
- hosts: all
  become: yes
  tasks:
    - name: Insatll apache on ubuntu
      apt: name=apache2 state=present
      when: ansible_os_family== "Debian"
      ignore_errors: True

    - name: Insatll httpd on Red Hat
      yum: name=httpd state=present
      when: ansible_os_family== "RedHat"
      ignore_errors: True

